import React from 'react';
import { getFileUrl } from '../services/api';

/**
 * Checks if a URL or filename represents an image.
 */
export function isImageUrl(url, filename) {
  if (!url && !filename) return false;
  const str = (filename || url || '').toLowerCase().split('?')[0];
  return (
    str.endsWith('.jpg') ||
    str.endsWith('.jpeg') ||
    str.endsWith('.png') ||
    str.endsWith('.gif') ||
    str.endsWith('.webp') ||
    str.endsWith('.svg') ||
    str.includes('image/')
  );
}

/**
 * Returns an appropriate emoji icon for a document or file type.
 */
export function getFileIcon(url, filename) {
  const str = (filename || url || '').toLowerCase();
  if (str.endsWith('.pdf')) return '📕';
  if (str.endsWith('.doc') || str.endsWith('.docx')) return '📘';
  if (str.endsWith('.xls') || str.endsWith('.xlsx')) return '📊';
  if (str.endsWith('.ppt') || str.endsWith('.pptx')) return '📙';
  if (str.endsWith('.zip') || str.endsWith('.rar')) return '🗜️';
  if (isImageUrl(url, filename)) return '🖼️';
  return '📎';
}

/**
 * Cleans ugly route strings (e.g. /uploads/WhatsApp_Image_...-1790778273209-663443253.jpeg)
 * into a human-friendly readable title.
 */
export function getCleanFileName(url, nome) {
  if (nome && typeof nome === 'string' && !nome.startsWith('/uploads/') && !nome.startsWith('http')) {
    return nome;
  }
  if (url && typeof url === 'string') {
    const parts = url.split('/');
    const last = parts[parts.length - 1];
    if (last) {
      // Remove trailing timestamp/hash suffix if generated by multer
      const withoutHash = last.replace(/-\d+-\d+(\.[a-zA-Z0-9]+)$/, '$1');
      return decodeURIComponent(withoutHash).replace(/_/g, ' ');
    }
  }
  return 'Documento Anexo';
}

/**
 * Universal Attachment Display:
 * - If image: Displays a clean thumbnail preview with click-to-expand.
 * - If document: Displays a clean document card with icon, friendly name and open link.
 * - Never shows raw route strings.
 */
export default function AttachmentDisplay({ url, nome, primaryColor = '#0055a4' }) {
  if (!url) return null;
  const fullUrl = getFileUrl(url);
  const cleanName = getCleanFileName(url, nome);
  const isImage = isImageUrl(url, nome);
  const icon = getFileIcon(url, nome);

  if (isImage) {
    return (
      <div style={{ marginTop: '0.75rem', paddingTop: '0.5rem', borderTop: '1px solid #f1f5f9' }}>
        <div
          style={{
            position: 'relative',
            borderRadius: '8px',
            overflow: 'hidden',
            border: '1px solid #e2e8f0',
            background: '#f8fafc',
            maxHeight: '170px',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <img
            src={fullUrl}
            alt={cleanName}
            style={{
              width: '100%',
              maxHeight: '170px',
              objectFit: 'cover',
              display: 'block',
              cursor: 'pointer',
              transition: 'transform 0.2s',
            }}
            onClick={() => window.open(fullUrl, '_blank')}
            onError={(e) => {
              e.target.style.display = 'none';
              if (e.target.nextSibling) e.target.nextSibling.style.display = 'flex';
            }}
          />
          <div
            style={{
              display: 'none',
              padding: '1rem',
              alignItems: 'center',
              gap: '0.5rem',
              fontSize: '0.8rem',
              color: '#64748b',
            }}
          >
            <span>🖼️</span> <span>{cleanName}</span>
          </div>
        </div>
        <div
          style={{
            marginTop: '0.35rem',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <span
            style={{
              fontSize: '0.74rem',
              color: '#64748b',
              fontWeight: 500,
              overflow: 'hidden',
              textOverflow: 'ellipsis',
              whiteSpace: 'nowrap',
              maxWidth: '70%',
            }}
          >
            {cleanName}
          </span>
          <a
            href={fullUrl}
            target="_blank"
            rel="noreferrer"
            style={{
              fontSize: '0.74rem',
              color: primaryColor,
              fontWeight: 600,
              textDecoration: 'none',
            }}
          >
            Ver imagem ↗
          </a>
        </div>
      </div>
    );
  }

  // Document Badge (PDF, DOCX, XLSX, etc.)
  return (
    <div style={{ marginTop: '0.6rem', paddingTop: '0.45rem', borderTop: '1px solid #f1f5f9' }}>
      <a
        href={fullUrl}
        target="_blank"
        rel="noreferrer"
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '0.45rem',
          padding: '0.35rem 0.65rem',
          background: '#f8fafc',
          borderRadius: '6px',
          fontSize: '0.78rem',
          color: '#0f172a',
          fontWeight: 600,
          textDecoration: 'none',
          border: '1px solid #e2e8f0',
          maxWidth: '100%',
          boxSizing: 'border-box',
        }}
      >
        <span style={{ fontSize: '1rem' }}>{icon}</span>
        <span
          style={{
            maxWidth: '190px',
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            whiteSpace: 'nowrap',
          }}
        >
          {cleanName}
        </span>
        <span style={{ color: primaryColor, fontSize: '0.72rem', marginLeft: 'auto' }}>↗</span>
      </a>
    </div>
  );
}
